services:
  app:
    container_name: nginx-dynamic
    build:
      context: .
    environment:
      - URL=http://backend:8000
    ports:
      - 80:80
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:80/health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3

  backend:
    image: python:3
    container_name: backend
    environment:
      - PYTHONUNBUFFERED=1
    command: /bin/bash -c "python3 -m http.server 8000"
    ports:
      - 8000:8000
